name: Guard code quality
 
on: [pull_request]
 
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
 
      - name: Build the app
        run: npm run build
 
      - name: Run Linter
        run: npm run lint
 
      - name: Run tests
        run: npm run test
 
      - name: Check tests coverage
        run: npm run test:cov
